// This is a file generated by the yeoman generator hapijs

/**
 * Dao layer which actually gets <%= name %> from the datastore
 *
 * @type {exports}
 */
var Boom = require('boom');

/**
 * Creates a <%= name %>
 *
 * @param payload - The data to be used to create a <%= name %>
 * @param callback
 */
exports.create = function (payload, callback) {
	// TODO: Implement dao method and call callback(null, <data>)
	return callback(Boom.notImplemented());
};

/**
 * Get's all <%= pluralName %>
 *
 * @param callback
 */
exports.find = function (callback) {
	// TODO: Implement dao method and call callback(null, <data>)
	return callback(Boom.notImplemented());
};

/**
 * Get's a specific <%= name %> by the id
 *
 * @param id  - The id of the <%= name %> to get
 * @param callback
 */
exports.findById = function (id, callback) {
	// TODO: Implement dao method and call callback(null, <data>)
	return callback(Boom.notImplemented());
};

/**
 * Updates a specific <%= name %>
 *
 * @param id      - The id of the <%= name %> to be updated
 * @param payload - The data to be updated
 * @param callback
 */
exports.update = function (id, payload, callback) {
	// TODO: Implement dao method and call callback(null, <data>)
	return callback(Boom.notImplemented());
};

/**
 * Remove a specific <%= name %>
 *
 * @param id      - The id of the <%= name %> to be deleted
 * @param callback
 */
exports.remove = function (id, callback) {
	// TODO: Implement dao method and call callback(null, <data>)
	return callback(Boom.notImplemented());
};

/* Add new methods above */