// This is a file generated by the yeoman generator hapijs

/**
 * All the endpoints for anything related to <%= name %>
 *
 * @type {exports}
 */
var Joi = require('Joi');
var <%= name %>Controller = require('./<%= name %>-ctrl');

module.exports = function() {
  return [
    {
      method: 'POST',
      path: '/<%= name %>/',
      config: {
        description: 'Creates a <%= name %>',
        handler: <%= name %>Controller.create<%= name %>,
        validate: {
          params: {

          },
          payload: {
            // TODO: Add some validations
          }
        }
      }
    },
    {
      method: 'GET',
      path: '/<%= name %>/',
      config : {
        description: 'Fetches all <%= name %>',
        handler: <%= name %>Controller.find<%= name %>,
        validate: {
          params: {

          },
          payload: {

          }
        }
      }
    },
    {
      method: 'GET',
      path: '/<%= name %>/{id}',
      config : {
        description: 'Fetches a <%= name %> by id',
        handler: <%= name %>Controller.find<%= name %>ById,
        validate: {
          params: {
            id: Joi.number().integer().required()
          },
          payload: {

          }
        }
      }
    },
    {
      method: 'PUT',
      path: '/<%= name %>/{id}',
      config : {
        description: 'Updates a <%= name %> for a specific id',
        handler: <%= name %>Controller.update<%= name %>,
        validate: {
          params: {
            id: Joi.number().integer().required()
          },
          payload: {
            // TODO: Add some validations
          }
        }
      }
    },
    {
      method: 'DELETE',
      path: '/<%= name %>/{id}',
      config : {
        description: 'Delete a <%= name %> for a specific id',
        handler: <%= name %>Controller.delete<%= name %>,
        validate: {
          params: {
            id: Joi.number().integer().required()
          },
          payload: {
            // TODO: Add some validations
          }
        }
      }
    }
  ]
}();