// This is a file generated by the yeoman generator hapijs

/**
 * Controller which handles requests/responses relating to <%= name %>
 *
 * @type {<%= name %>Dao|exports}
 */
var <%= daoName %> = require('./<%= name %>-dao');
var Boom = require('boom');

module.exports = function() {

  return {

    /**
     * Creates a <%= name %>
     *
     * @param req
     * @param reply
     */
    create: function create(req, reply) {

      <%= daoName %>.create(req.payload, function (err, data) {

        if (err) {
          return reply(Boom.badImplementation(err));
        }

        reply(data);
      });

    },

    /**
     * Gets all <%= pluralName %>
     *
     * @param req
     * @param reply
     */
    find: function find(req, reply) {

      <%= daoName %>.find(function (err, data) {

        if (err) {
          return reply(Boom.badImplementation(err));
        }

        reply(data);
      });
    },

    /**
     * Get a specific <%= name %> by id
     *
     * @param req
     * @param reply
     */
    findById: function findById(req, reply) {

      <%= daoName %>.findById(req.params.id, function (err, data) {

        if (err) {
          return reply(Boom.badImplementation(err));
        }

        reply(data);
      });
    },

    /**
     * Update a specific <%= name %> by id
     *
     * @param req
     * @param reply
     */
    update: function update(req, reply) {

      <%= daoName %>.update(req.params.id, req.payload, function (err, data) {

        if (err) {
          return reply(Boom.badImplementation(err));
        }

        reply(data);
      });
    },
		
    /**
     * Remove a specific <%= name %> by id
     *
     * @param req
     * @param reply
     */
    remove: function remove(req, reply) {

      <%= daoName %>.remove(req.params.id, function (err, data) {

        if (err) {
          return reply(Boom.badImplementation(err));
        }

        reply(data);
      });
    }
  }

}();
