// This is a file generated by the yeoman generator hapijs

/**
 * Controller which handles requests/responses relating to <%= name %>
 *
 * @type {<%= name %>Dao|exports}
 */
var SOMETHINGDao = require('./SOMETHING-dao');

module.exports = function() {

  return {

    /**
     * Creates a <%= name %>
     *
     * @param req
     * @param reply
     */
    createSOMETHING: function createSOMETHING(req, reply) {

      SOMETHINGDao.createSOMETHING(req.params.id, req.payload, function (err, data) {

        if (err) {
          reply(Boom.badImplementation(err));
        }

        reply(data);
      });

    },

    /**
     * Gets all SOMETHING
     *
     * @param req
     * @param reply
     */
    findSOMETHING: function findSOMETHING(req, reply) {

      SOMETHINGDao.findSOMETHING(req.params.id, req.payload, function (err, data) {

        if (err) {
          reply(Boom.badImplementation(err));
        }

        reply(data);
      });
    },

    /**
     * Get a specific SOMETHING by id
     *
     * @param req
     * @param reply
     */
    findSOMETHINGById: function findSOMETHINGById(req, reply) {

      SOMETHINGDao.findSOMETHINGById(req.params.id, req.payload, function (err, data) {

        if (err) {
          reply(Boom.badImplementation(err));
        }

        reply(data);
      });
    },

    /**
     * Update a specific SOMETHING by id
     *
     * @param req
     * @param reply
     */
    updateSOMETHING: function updateSOMETHING(req, reply) {

      SOMETHINGDao.updateSOMETHING(req.params.id, req.payload, function (err, data) {

        if (err) {
          reply(Boom.badImplementation(err));
        }

        reply(data);
      });
    }
  }

}();
