// This is a file generated by the yeoman generator hapijs

/**
 * All the endpoints for anything related to SOMETHING
 *
 * @type {exports}
 */
var Joi = require('Joi');
var SOMETHINGController = require('./SOMETHING-ctrl');

module.exports = function() {
  return [
    {
      method: 'POST',
      path: '/SOMETHING/',
      config: {
        description: 'Creates a SOMETHING',
        handler: SOMETHINGController.createSOMETHING,
        validate: {
          params: {

          },
          payload: {
            // TODO: Add some validations
          }
        }
      }
    },
    {
      method: 'GET',
      path: '/SOMETHING/',
      config : {
        description: 'Fetches all SOMETHING',
        handler: SOMETHINGController.findSOMETHING,
        validate: {
          params: {

          },
          payload: {

          }
        }
      }
    },
    {
      method: 'GET',
      path: '/SOMETHING/{id}',
      config : {
        description: 'Fetches a SOMETHING by id',
        handler: SOMETHINGController.findSOMETHINGById,
        validate: {
          params: {
            id: Joi.number().integer().required()
          },
          payload: {

          }
        }
      }
    },
    {
      method: 'PUT',
      path: '/SOMETHING/{id}',
      config : {
        description: 'Updates a SOMETHING for a specific id',
        handler: SOMETHINGController.updateSOMETHING,
        validate: {
          params: {
            id: Joi.number().integer().required()
          },
          payload: {
            // TODO: Add some validations
          }
        }
      }
    }
  ]
}();