// This is a file generated by the yeoman generator hapijs

/**
 * Dao layer which actually gets SOMETHING from the datastore
 *
 * @type {exports}
 */

module.exports = function() {

  return {

    /**
     * Creates a SOMETHING
     *
     * @param payload - The data to be used to create a SOMETHING
     * @param callback
     */
    createSOMETHING: function createSOMETHING(payload, callback) {
      // TODO: Implement dao method and call callback(null, <data>)
    },

    /**
     * Find all SOMETHING
     *
     * @param callback
     */
    findTasksByPatientId: function findTasksByPatientId(callback) {
      // TODO: Implement dao method and call callback(null, <data>)
    },

    /**
     * Get's all SOMETHING
     *
     * @param callback
     */
    findSOMETHING: function findTasksForUser(callback) {
      // TODO: Implement dao method and call callback(null, <data>)
    },

    /**
     * Get's a specific SOMETHING by the id
     *
     * @param id  - The id of the SOMETHING to get
     * @param callback
     */
    findSOMETHINGById: function findTaskById(id, callback) {
      // TODO: Implement dao method and call callback(null, <data>)
    },

    /**
     * Updates a specific SOMETHING
     *
     * @param id      - The id of the SOMETHING to be updated
     * @param payload - The data to be updated
     * @param callback
     */
    updateSOMETHING: function updateSOMETHING(id, payload, callback) {
      // TODO: Implement dao method and call callback(null, <data>)
    }
  }

}();
