// This is a file generated by the yeoman generator hapijs

/**
 * Dao layer which actually gets <%= name %> from the datastore
 *
 * @type {exports}
 */

module.exports = function() {

  return {

    /**
     * Creates a <%= name %>
     *
     * @param payload - The data to be used to create a <%= name %>
     * @param callback
     */
    create: function create(payload, callback) {
      // TODO: Implement dao method and call callback(null, <data>)
    },

    /**
     * Get's all <%= pluralName %>
     *
     * @param callback
     */
    find: function find(callback) {
      // TODO: Implement dao method and call callback(null, <data>)
    },

    /**
     * Get's a specific <%= name %> by the id
     *
     * @param id  - The id of the <%= name %> to get
     * @param callback
     */
    findById: function findById(id, callback) {
      // TODO: Implement dao method and call callback(null, <data>)
    },

    /**
     * Updates a specific <%= name %>
     *
     * @param id      - The id of the <%= name %> to be updated
     * @param payload - The data to be updated
     * @param callback
     */
    update: function update(id, payload, callback) {
      // TODO: Implement dao method and call callback(null, <data>)
    },
		
    /**
     * Remove a specific <%= name %>
     *
     * @param id      - The id of the <%= name %> to be deleted
     * @param callback
     */
    remove: function remove(id, callback) {
      // TODO: Implement dao method and call callback(null, <data>)
    }
  }

}();
