// This is a file generated by the yeoman generator hapijs

/**
 * Unit tests for all the SOMETHING endpoints
 *
 * @type {exports}
 */

var Lab = require('lab');
var server = require('../');

/**
 * All the tests related to tasks
 */
Lab.experiment('Creating SOMETHING', function() {

  Lab.test('should be successful', function (done) {
    var options = {
      method: 'POST',
      url: '/SOMETHING',
      payload: {

      }
    };

    server.inject(options, function (response) {
      var result = response.result;

      Lab.expect(response.statusCode).to.equal(200);

      done();
    });
  });

});

Lab.experiment('Fetching SOMETHING', function() {

  Lab.test('should be successful', function (done) {
    var options = {
      method: 'GET',
      url: '/SOMETHING',
      payload: {

      }
    };

    server.inject(options, function (response) {
      var result = response.result;

      Lab.expect(response.statusCode).to.equal(200);

      done();
    });
  });

});

